// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-i6dL84uxmPcMOtl1-MkH33e0KUwMxHc',
    appId: '1:835275258842:web:d87d3a4645431321f91ee3',
    messagingSenderId: '835275258842',
    projectId: 'game-diary-908c0',
    authDomain: 'game-diary-908c0.firebaseapp.com',
    storageBucket: 'game-diary-908c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZznRTZiGyllK-1F3LHg6RPxcClftuzfE',
    appId: '1:835275258842:android:91f43767012c926ef91ee3',
    messagingSenderId: '835275258842',
    projectId: 'game-diary-908c0',
    storageBucket: 'game-diary-908c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyrZFOkcKxzAob8eqrVy6of4Ad8pk-jyk',
    appId: '1:835275258842:ios:ab662a5afc2c487ff91ee3',
    messagingSenderId: '835275258842',
    projectId: 'game-diary-908c0',
    storageBucket: 'game-diary-908c0.firebasestorage.app',
    iosBundleId: 'com.example.gameDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyrZFOkcKxzAob8eqrVy6of4Ad8pk-jyk',
    appId: '1:835275258842:ios:ab662a5afc2c487ff91ee3',
    messagingSenderId: '835275258842',
    projectId: 'game-diary-908c0',
    storageBucket: 'game-diary-908c0.firebasestorage.app',
    iosBundleId: 'com.example.gameDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-i6dL84uxmPcMOtl1-MkH33e0KUwMxHc',
    appId: '1:835275258842:web:910acde579b74aeef91ee3',
    messagingSenderId: '835275258842',
    projectId: 'game-diary-908c0',
    authDomain: 'game-diary-908c0.firebaseapp.com',
    storageBucket: 'game-diary-908c0.firebasestorage.app',
  );
}
